/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ewb;

import chat.studentChat;
import chat.teacherChat;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.UnknownHostException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import student_window.studentMain;
import teacher_window.MainWindow;
import teacher_window.Screen_capture;

/**
 *
 * @author RADHIKA
 */
public class LogInForm extends javax.swing.JFrame {
         //DBMS d=new DBMS();
         static RmiInterface ri;
         static Registry r;
         String sql="";
         String password="";
    /**
     * Creates new form LogInForm
     */
    public LogInForm() {
        //setExtendedState(MAXIMIZED_BOTH);
        try{
           //System.setProperty("netbeans.security.nocheck", "false"); 
            r=LocateRegistry.getRegistry("localhost",9087);
            ri=(RmiInterface)(r.lookup("yank"));
            //System.setSecurityManager(new RMISecurityManager());
            
        }
        catch(RemoteException | NotBoundException | HeadlessException e){
            
            JOptionPane.showMessageDialog(null,e.toString());
        }
        
        SetUI();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        double width = screenSize.getWidth();
        double height = screenSize.getHeight();
        int x_dim=(int)(width)/3;
        int y_dim=(int) ((height)/1.5);
        int y2_dim=(int) ((height - y_dim)/2);
        setBounds(x_dim, y2_dim, x_dim, y_dim);
        Dimension dm=new Dimension(x_dim, y_dim);
        setMinimumSize(dm);
        initComponents();
        this.setVisible(true);
    }
    
    public static void SetUI(){
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            //java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        l_un = new javax.swing.JLabel();
        t_un = new javax.swing.JTextField();
        l_type = new javax.swing.JLabel();
        cb_type = new javax.swing.JComboBox();
        l_psw = new javax.swing.JLabel();
        t_psw = new javax.swing.JTextField();
        l_msg = new javax.swing.JLabel();
        b_login = new javax.swing.JButton();
        b_reg = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setUndecorated(true);
        getContentPane().setLayout(null);

        login.setOpaque(false);

        label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        label.setForeground(new java.awt.Color(255, 255, 255));
        label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label.setText("LOG IN");
        label.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        l_un.setForeground(new java.awt.Color(255, 255, 255));
        l_un.setText("UserName :");

        l_type.setForeground(new java.awt.Color(255, 255, 255));
        l_type.setText("Type :");

        cb_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TEACHER", "STUDENT" }));

        l_psw.setForeground(new java.awt.Color(255, 255, 255));
        l_psw.setText("Password :");

        l_msg.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_msg.setForeground(new java.awt.Color(255, 0, 0));

        b_login.setText("Log In");
        b_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_loginActionPerformed(evt);
            }
        });

        b_reg.setText("Registration");
        b_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_regActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1788, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t_un, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(cb_type, 0, 240, Short.MAX_VALUE)
                            .addGroup(loginLayout.createSequentialGroup()
                                .addComponent(b_login, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(b_reg))
                            .addComponent(t_psw, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(l_msg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l_psw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l_type, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l_un, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        loginLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cb_type, l_msg, l_psw, l_type, l_un, t_psw, t_un});

        loginLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {b_login, b_reg});

        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(l_un)
                .addGap(18, 18, 18)
                .addComponent(t_un, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(l_type)
                .addGap(18, 18, 18)
                .addComponent(cb_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(l_psw)
                .addGap(18, 18, 18)
                .addComponent(t_psw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(l_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_login)
                    .addComponent(b_reg))
                .addGap(46, 46, 46))
        );

        loginLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {b_login, b_reg, cb_type, t_psw, t_un});

        loginLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {l_psw, l_un});

        getContentPane().add(login);
        login.setBounds(0, 0, 430, 470);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.jpg"))); // NOI18N
        jLabel2.setAlignmentY(0.0F);
        jLabel2.setMaximumSize(new java.awt.Dimension(20, 20));
        jLabel2.setMinimumSize(new java.awt.Dimension(20, 20));
        jLabel2.setPreferredSize(getPreferredSize());
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 570, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reset_all(){
        t_un.setText(null);
        t_psw.setText(null);
        cb_type.setSelectedIndex(0);
        l_msg.setText(null);
    }
    
    private void b_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_regActionPerformed
        reset_all();
        this.setVisible(false);
        EWB.rf.setVisible(true);
    }//GEN-LAST:event_b_regActionPerformed

    private void login() throws UnknownHostException, IOException{
        l_msg.setText(null);
        EWB.is = new Image_share();
        if(!"".equals(t_un.getText()) && !"".equals(t_psw.getText())){
            if(cb_type.getSelectedItem() == "TEACHER" || cb_type.getSelectedItem() == "teacher"){
                this.setVisible(false);
                EWB.tm = new MainWindow();
                EWB.tm.setVisible(true);
                EWB.teacherChat = new teacherChat(t_un.getText());
                EWB.sc = new Screen_capture();
                Thread tsc = new Thread(EWB.sc);
                tsc.start();
                EWB.lif.dispose();
                EWB.rf.dispose();
            }
            
            else if(cb_type.getSelectedItem() == "STUDENT"){
                this.setVisible(false);
                //EWB.sm.setVisible(true);
                EWB.studentChat = new studentChat(t_un.getText());
                EWB.sm = new studentMain();
                Thread tsm = new Thread(EWB.sm);
                tsm.start();
                EWB.lif.dispose();
                EWB.rf.dispose();
            }
            
        }   
        else
            l_msg.setText("Please Enter UserName and/or Password");
    }
    
    private void b_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_loginActionPerformed
        l_msg.setText(null);
       // DBMS d = new DBMS();
        
        if("".equals(t_un.getText()) && "".equals(t_psw.getText())){
             l_msg.setText("Please Enter UserName and/or Password");
        }
        String un=t_un.getText();
        String psw=t_psw.getText();
        String type=cb_type.getSelectedItem().toString();
        System.out.println(type);
        sql="select * from login where id = '"+un+"' AND type = '"+type+"'";
        login_details ld;
        try {
            ld = ri.generalSelectQuery(sql);
            if(ld!=null){
                password=ld.pass;
            }
            else if(ld==null){
                JOptionPane.showMessageDialog(this, "Check User name and/or Password...", "Login Failed", ERROR);
            }
        } catch (RemoteException | HeadlessException ex) {
            Logger.getLogger(LogInForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        if(psw.equals(password)){
            try {
                login();
            } catch (UnknownHostException ex) {
                Logger.getLogger(LogInForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(LogInForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        else{
            System.out.println("error in database");
        }
        
    }//GEN-LAST:event_b_loginActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_login;
    private javax.swing.JButton b_reg;
    private javax.swing.JComboBox cb_type;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel l_msg;
    private javax.swing.JLabel l_psw;
    private javax.swing.JLabel l_type;
    private javax.swing.JLabel l_un;
    private javax.swing.JLabel label;
    private javax.swing.JPanel login;
    private javax.swing.JTextField t_psw;
    private javax.swing.JTextField t_un;
    // End of variables declaration//GEN-END:variables

    

}
