package ewb;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.rmi.NotBoundException;
import java.rmi.RMISecurityManager;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author RADHIKA
 */
public class Reg_Form extends javax.swing.JFrame {
    static RmiInterface ri;
    static Registry r;
    String sql="";
    String sql1="";
    //DBMS d=new DBMS();
    /**
     * Creates new form LogInForm
     */
    public Reg_Form() {
        //setExtendedState(MAXIMIZED_BOTH);
        try{
            r=LocateRegistry.getRegistry("localhost",9087);
            ri=(RmiInterface)(r.lookup("yank"));
            //System.setSecurityManager(new RMISecurityManager());
             //System.setProperty("netbeans.security.nocheck", "true"); 
        }
        catch(RemoteException | NotBoundException | HeadlessException e){
            JOptionPane.showMessageDialog(null,e.toString());
        }
        
        LogInForm.SetUI();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        double width = screenSize.getWidth();
        double height = screenSize.getHeight();
        int x_dim=(int)(width)/3;
        int y_dim=(int) ((height)/1.2);
        int y2_dim=(int) ((height - y_dim)/2);
        setBounds(x_dim, y2_dim, x_dim, y_dim);
        Dimension dm=new Dimension(x_dim, y_dim);
        setMinimumSize(dm);
//        c_branch.setEnabled(false);
//        c_sem.setEnabled(false);
        initComponents();
        
        
    }
    
    
    int ValidatePhoneNumber (){
        int i=0;
         String sPhoneNumber = t_cno.getText();
      
         Pattern pattern = Pattern.compile("\\d{10}");
         Matcher matcher = pattern.matcher(sPhoneNumber);
        
      if (matcher.matches()) {
    	  System.out.println("Phone Number Valid");
           }
      else {
    	  System.out.println("Phone Number must be in the form XXX-XXXXXXX");
          i=1;
      }
      return i;
 }

    int ValidateEmailid (){
        int j=0;
         String Email =t_eid.getText();
          final String EMAIL_PATTERN = 
		"^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
		+ "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
 
        Pattern pattern = Pattern.compile(EMAIL_PATTERN);
        Matcher matcher =pattern.matcher( Email );
             if (matcher.matches()) {
                 System.out.println("Email is Valid");
                }
             else
             {
        	  System.out.println("Email is must be in the form XXX-XXXXXXX");
                  j=1;
             }
      return j;
 }

         
    int checkall(){
         int flag=0;
         int P=ValidatePhoneNumber();
         int E=ValidateEmailid();
          l_msg.setText("REQUIRED FIELDS");
            l_msg.setForeground(Color.red);
            if("".equals(t_userid.getText())){
                l_userid.setForeground(Color.red);
            }
            if("".equals(t_psw.getText())){
                l_psw.setForeground(Color.red);
            }
            if("".equals(t_psw2.getText())){
                l_psw2.setForeground(Color.red);
            }
            if("".equals(t_fn.getText())){
                l_fn.setForeground(Color.red);
            }
            if("".equals(t_ln.getText())){
                l_ln.setForeground(Color.red);
            }
            if("".equals(t_cno.getText())){
                l_cno.setForeground(Color.red);
            }
            if("".equals(t_eid.getText())){
                l_eid.setForeground(Color.red);
            }
          if(!t_psw.getText().equals(t_psw2.getText())){
                flag=1;
                JOptionPane.showMessageDialog(null, "password is invalid ");
            }
          if(P!=0){
              flag=1;
              JOptionPane.showMessageDialog(null, "phone number is invalid "); 
          }
          if(E!=0){
              flag=1;
              JOptionPane.showMessageDialog(null, "Email id is invalid "); 
          } 
          return flag;
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        l_type = new javax.swing.JLabel();
        c_type = new javax.swing.JComboBox();
        l_userid = new javax.swing.JLabel();
        t_userid = new javax.swing.JTextField();
        l_psw = new javax.swing.JLabel();
        l_psw2 = new javax.swing.JLabel();
        l_fn = new javax.swing.JLabel();
        t_fn = new javax.swing.JTextField();
        l_ln = new javax.swing.JLabel();
        t_ln = new javax.swing.JTextField();
        l_cno = new javax.swing.JLabel();
        t_cno = new javax.swing.JTextField();
        l_eid = new javax.swing.JLabel();
        t_eid = new javax.swing.JTextField();
        l_branch = new javax.swing.JLabel();
        c_branch = new javax.swing.JComboBox();
        l_sem = new javax.swing.JLabel();
        c_sem = new javax.swing.JComboBox();
        l_msg = new javax.swing.JLabel();
        save_btn = new javax.swing.JButton();
        reset_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        t_psw = new javax.swing.JPasswordField();
        t_psw2 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setUndecorated(true);
        getContentPane().setLayout(null);

        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setOpaque(false);

        label.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        label.setForeground(new java.awt.Color(255, 255, 255));
        label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label.setText("REGISTRATION FORM ");
        label.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        l_type.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_type.setForeground(new java.awt.Color(255, 255, 255));
        l_type.setText("Type :");

        c_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "STUDENT", "TEACHER", "ADMIN" }));
        c_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_typeActionPerformed(evt);
            }
        });

        l_userid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_userid.setForeground(new java.awt.Color(255, 255, 255));
        l_userid.setText("User Id :");

        l_psw.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_psw.setForeground(new java.awt.Color(255, 255, 255));
        l_psw.setText("Password :");

        l_psw2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_psw2.setForeground(new java.awt.Color(255, 255, 255));
        l_psw2.setText("Confirm Password :");

        l_fn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_fn.setForeground(new java.awt.Color(255, 255, 255));
        l_fn.setText("First Name :");

        l_ln.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_ln.setForeground(new java.awt.Color(255, 255, 255));
        l_ln.setText("Last Name :");

        l_cno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_cno.setForeground(new java.awt.Color(255, 255, 255));
        l_cno.setText("Contact No :");

        l_eid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_eid.setForeground(new java.awt.Color(255, 255, 255));
        l_eid.setText("Email Id :");

        l_branch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_branch.setForeground(new java.awt.Color(255, 255, 255));
        l_branch.setText("Branch :");

        c_branch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Computer", "I.T.", " " }));

        l_sem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_sem.setForeground(new java.awt.Color(255, 255, 255));
        l_sem.setText("Semester :");

        c_sem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));

        save_btn.setText("SAVE");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });

        reset_btn.setText("RESET");
        reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_btnActionPerformed(evt);
            }
        });

        back_btn.setText("BACK");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1788, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label)
                            .addGroup(loginLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(l_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(loginLayout.createSequentialGroup()
                                        .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(l_type, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(l_userid, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(l_psw, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(l_psw2)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(l_ln, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(l_fn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(l_cno, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(l_sem, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(l_branch, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(l_eid, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(41, 41, 41)
                                        .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(t_fn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(t_ln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(t_cno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(c_branch, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(t_eid, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(c_sem, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(t_userid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(c_type, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(t_psw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(t_psw2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(save_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reset_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(back_btn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        loginLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {c_branch, c_sem, c_type, t_cno, t_eid, t_fn, t_ln, t_psw, t_psw2, t_userid});

        loginLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {l_branch, l_cno, l_eid, l_fn, l_ln, l_psw, l_psw2, l_sem, l_type, l_userid});

        loginLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {back_btn, reset_btn, save_btn});

        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_type, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t_userid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_userid, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_psw, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_psw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_psw2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_psw2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_fn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_fn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_ln, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_ln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_cno, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_cno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_eid, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_eid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_branch, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(c_branch)))
                .addGap(18, 18, 18)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_sem, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_sem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(l_msg)
                .addGap(18, 18, 18)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back_btn))
                .addGap(91, 91, 91))
        );

        loginLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {c_sem, c_type, t_cno, t_eid, t_fn, t_ln, t_psw, t_psw2, t_userid});

        loginLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {l_branch, l_cno, l_eid, l_fn, l_ln, l_msg, l_psw, l_psw2, l_sem, l_type, l_userid});

        loginLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {back_btn, reset_btn, save_btn});

        getContentPane().add(login);
        login.setBounds(0, 0, 430, 650);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.jpg"))); // NOI18N
        jLabel2.setAlignmentY(0.0F);
        jLabel2.setMaximumSize(new java.awt.Dimension(20, 20));
        jLabel2.setMinimumSize(new java.awt.Dimension(20, 20));
        jLabel2.setPreferredSize(getPreferredSize());
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 570, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        int k=checkall();
        String s1 = t_userid.getText();
        String s2 = t_fn.getText();
        String s3 = t_ln.getText();
        String s4 = t_cno.getText();
        String s5 = t_eid.getText();
        String s6 = c_branch.getSelectedItem().toString();
        String s9 = c_type.getSelectedItem().toString();
        int s7=Integer.valueOf((String)(c_sem.getSelectedItem()));
        String s8 = t_psw.getText();
       // System.out.println("1"+s1+"2"+s2+"3"+s3+"4"+s4+"5"+s5+"6"+s6+"7"+s7);
   
        l_msg.setText(null);
      /*  if(t_userid.getText() == null && t_psw.getText() == null && t_psw2.getText() == null && t_fn.getText() == null && t_ln.getText() == null && t_cno.getText() == null && t_eid.getText() == null){
          
          } */ 
        if(k==0){
               //DBMS d=new DBMS();
               sql1="insert into login values ('"+s1+"','"+s8+"','"+s9+"')";
               String t=(String)c_type.getSelectedItem();
               System.out.println(t);
               if("Student".equalsIgnoreCase(t)){
                  sql="insert into student(S_id,F_name,L_name,Contact_no,Mail_id,Branch,Sem) values('"+s1+"','"+s2+"','"+s3+"','"+s4+"','"+s5+"','"+s6+"','"+s7+"')";
               }
               else if("Teacher".equalsIgnoreCase(t)){
                   sql="insert into teacher(T_id,F_name,L_name,Contact_no,Mail_id) values('"+s1+"','"+s2+"','"+s3+"','"+s4+"','"+s5+"')";
               }
               else if("ADMIN".equalsIgnoreCase(t)){
                   sql="insert into admin(A_id,F_name,L_name,Contact_no,Mail_id) values('"+s1+"','"+s2+"','"+s3+"','"+s4+"','"+s5+"')";
               }
               
               int j=0;
                
               try {
                    j = ri.generalInsertUpdateDeleteQuery(sql1);
               } catch (RemoteException ex) {
                    Logger.getLogger(Reg_Form.class.getName()).log(Level.SEVERE, null, ex);
               }
              
               if(j==1){
                   JOptionPane.showMessageDialog(Reg_Form.this,"login details Saved Successfully");
               }
               else{
                     JOptionPane.showMessageDialog(Reg_Form.this,"login details Data Not Saved Due to some Error");
               }
               
               int i=0;
               try {
                    i = ri.generalInsertUpdateDeleteQuery(sql);
               } catch (RemoteException ex) {
                    Logger.getLogger(Reg_Form.class.getName()).log(Level.SEVERE, null, ex);
               }
              
               if(i==1){
                   JOptionPane.showMessageDialog(Reg_Form.this,"Saved Successfully");
                }
               else{
                     JOptionPane.showMessageDialog(Reg_Form.this,"Data Not Saved Due to some Error");
                 }
            }    
       
    }//GEN-LAST:event_save_btnActionPerformed
    
    private void reset_all(){
        t_userid.setText(null);
        t_psw.setText(null);
        t_psw2.setText(null);
        t_fn.setText(null);
        t_ln.setText(null);
        t_cno.setText(null);
        t_eid.setText(null);
        c_type.setSelectedIndex(0);
        c_branch.setSelectedIndex(0);
        c_type.setSelectedIndex(0);
        l_msg.setText(null);
        l_userid.setForeground(Color.WHITE);
        l_psw.setForeground(Color.WHITE);
        l_psw2.setForeground(Color.WHITE);
        l_fn.setForeground(Color.WHITE);
        l_ln.setForeground(Color.WHITE);
        l_cno.setForeground(Color.WHITE);
        l_eid.setForeground(Color.WHITE);
        
    }
    
    private void reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_btnActionPerformed
        reset_all();
    }//GEN-LAST:event_reset_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        reset_all();
        this.setVisible(false);
        EWB.lif.setVisible(true);
    }//GEN-LAST:event_back_btnActionPerformed

    private void c_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_typeActionPerformed
        // TODO add your handling code here:
      String t=c_type.getSelectedItem().toString();
        switch (t) {
            case "TEACHER":
                c_branch.setEnabled(false);
                c_sem.setEnabled(false);
                break;
            case "ADMIN":
                c_branch.setEnabled(false);
                c_sem.setEnabled(false);
                break;
            default:
                c_branch.setEnabled(true);
                c_sem.setEnabled(true);
                break;
        }
    }//GEN-LAST:event_c_typeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JComboBox c_branch;
    private javax.swing.JComboBox c_sem;
    private javax.swing.JComboBox c_type;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel l_branch;
    private javax.swing.JLabel l_cno;
    private javax.swing.JLabel l_eid;
    private javax.swing.JLabel l_fn;
    private javax.swing.JLabel l_ln;
    private javax.swing.JLabel l_msg;
    private javax.swing.JLabel l_psw;
    private javax.swing.JLabel l_psw2;
    private javax.swing.JLabel l_sem;
    private javax.swing.JLabel l_type;
    private javax.swing.JLabel l_userid;
    private javax.swing.JLabel label;
    private javax.swing.JPanel login;
    private javax.swing.JButton reset_btn;
    private javax.swing.JButton save_btn;
    private javax.swing.JTextField t_cno;
    private javax.swing.JTextField t_eid;
    private javax.swing.JTextField t_fn;
    private javax.swing.JTextField t_ln;
    private javax.swing.JPasswordField t_psw;
    private javax.swing.JPasswordField t_psw2;
    private javax.swing.JTextField t_userid;
    // End of variables declaration//GEN-END:variables

        public static void main(String args[]){
        
    }
}