/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package chat;

import ewb.EWB;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.ArrayList;
import javax.swing.JFrame;


/**
 *
 * @author shraddha
 */
public class teacherChat extends JFrame {

    /**
     * Creates new form teacherChat
     */
    
    static String msg;
    static String username;
    static Socket client;
    static PrintWriter p;
    static byte[] buffer;
    static ArrayList student_list;
    public teacherChat(String user_name) throws UnknownHostException, IOException {
        teacherChat.username = user_name;
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        initComponents();
        Dimension screensize = Toolkit.getDefaultToolkit().getScreenSize();
        int width = (int) screensize.getWidth();
        int height = (int) screensize.getHeight();
        this.setBounds(0, (int)(4*height/5), width, (int)height/5);
        this.setVisible(true);
        client=new Socket("localhost", 8765);
        if(client!=null){
            System.out.println("connected to Server !!");
        }
        teac_Listener l=new teac_Listener(client);
        Thread t=new Thread(l);
        t.start();
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
              //new teacherChat("yank").setVisible(true);  
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jb = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        stud_list = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta = new javax.swing.JTextArea();
        jtf = new javax.swing.JTextField();
        exit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jb.setText("SEND");
        jb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActionPerformed(evt);
            }
        });
        getContentPane().add(jb);
        jb.setBounds(1130, 120, 110, 30);

        stud_list.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(stud_list);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(1250, 10, 110, 100);

        jta.setColumns(20);
        jta.setEditable(false);
        jta.setRows(5);
        jScrollPane1.setViewportView(jta);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 1230, 100);

        jtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfActionPerformed(evt);
            }
        });
        getContentPane().add(jtf);
        jtf.setBounds(10, 120, 1100, 30);

        exit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exit.setForeground(new java.awt.Color(204, 0, 0));
        exit.setText("EXIT");
        exit.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(204, 0, 0)));
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(1250, 120, 110, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-4, -6, 3750, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActionPerformed
        if(!jtf.getText().equals("")){
                try {
                    String d;
                    d = jtf.getText();
                    jtf.setText("");
                    msg=username +" :- "+d;

                    p=new PrintWriter(client.getOutputStream());
                    p.println(msg);
                    p.flush();

                } catch (IOException ex) {}
        }
    }//GEN-LAST:event_jbActionPerformed

    private void jtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfActionPerformed
        if(!jtf.getText().equals("")){
                try {
                    String d;
                    d = jtf.getText();
                    jtf.setText("");
                    msg=username +" :- "+d;

                    p=new PrintWriter(client.getOutputStream());
                    p.println(msg);
                    p.flush();

                } catch (IOException ex) {}
          }
    }//GEN-LAST:event_jtfActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.dispose();
        ewb.EWB.tm.dispose();
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnknownHostException, IOException {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teacherChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teacherChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teacherChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teacherChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        //teacherChat c = new teacherChat();
      /*  client=new Socket("localhost", 8765);
        if(client!=null){
            System.out.println("connected to Server !!");
        }
        teac_Listener l=new teac_Listener(client);
        Thread t=new Thread(l);
        t.start();
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
              //new teacherChat("yank").setVisible(true);  
            }
        });
        * 
        */
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    static javax.swing.JButton jb;
    static javax.swing.JTextArea jta;
    static javax.swing.JTextField jtf;
    static javax.swing.JList stud_list;
    // End of variables declaration//GEN-END:variables
}

class teac_Listener implements Runnable{
    
    Socket client;
    BufferedReader reader;
    String str;
    teac_Listener (Socket client){
        this.client=client;
    }
    @Override
    public void run() {
        try {
            InputStreamReader r = new InputStreamReader(client.getInputStream());
            reader=new BufferedReader(r);

            while((str=reader.readLine())!=null){
                teacherChat.jta.append("\n"+str);
            }
        } catch (IOException ex) {
            //Logger.getLogger(Listener.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
